### ISSUE TITLE
BookCorpus no longer provides data sets

### ISSUE THREAD

**Issue by funqc** [zhegan27/ConvSent#1]
BookCorpus (http://yknzhu.wixsite.com/mbweb) no longer provides data sets, and I have not found it online. Do you still have a backup of the data set? Can you send me a copy of the data?

**Comment by zhegan27** [comment]
can you send an email to zhe.gan@microsoft.com?

**Comment by funqc** [comment]
> can you send an email to [zhe.gan@microsoft.com](mailto:zhe.gan@microsoft.com)?

I have sent an email to you, thank you

**Comment by xuwenshen** [comment]
hi, have you already gotten it? 
if yes, can you send me a copy one? thank you
